function Hd = FirFilter300Hz
%FIRFILTER300HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
% Generated on: 26-Jun-2017 13:35:55

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 30000;  % Sampling Frequency

N    = 120;       % Order 256
Fc1  = 300;      % First Cutoff Frequency
Fc2  = 8000;     % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = hamming(N+1);
%win = hann(N+1);
%win = blackman(N+1);
%win = rectwin(N+1);
%win = flattopwin(N+1);
%win = triang(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
